package net.mv.expectedException;

import org.junit.Test;

public class JUnitTest2 {

	@Test
	public void divisionWithException() {
		int num = 1/0;
	}
}
